name: flutter_frontend
description: "An AI assistant for Dental Doctors."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.13.1  # Fixed indentation
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/   

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"  # For adaptive icons
  adaptive_icon_background: "#FFFFFF"  # Background color (white)
  min_sdk_android: 21  # Required for adaptive icons
